# get the base node image
FROM node:16.13.0-alpine as builder

# set the working dir for container
WORKDIR /react-frontend

# copy the json file first
COPY ./package.json package-*.lock ./

# install npm dependencies
RUN npm install

# copy other project files
COPY . .

# build the folder
CMD [ "npm", "start" ]