# get the base node image
FROM node:16.13.0-alpine as builder

# set the working dir for container
WORKDIR /react-frontend

# copy the json file first
COPY ./package.json npm-shrinkwrap.json ./

# install npm dependencies
RUN npm install

# copy other project files
COPY . .

# build the folder
RUN npm run build:staging

# Handle Nginx
FROM nginx:1.21.6-alpine
COPY --from=builder /react-frontend/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf